// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20260914134813_ExpandCarFleet")]
    partial class ExpandCarFleet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=85",
                            Model = "5 Series",
                            PricePerDay = 95m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes",
                            CategoryId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=85",
                            Model = "C Class",
                            PricePerDay = 120m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Toyota",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=85",
                            Model = "RAV4",
                            PricePerDay = 65m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Audi",
                            CategoryId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85",
                            Model = "A6",
                            PricePerDay = 110m,
                            Status = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=900&q=85",
                            Model = "X5",
                            PricePerDay = 105m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Toyota",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=85",
                            Model = "Camry",
                            PricePerDay = 55m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Toyota",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=900&q=85",
                            Model = "Corolla",
                            PricePerDay = 45m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Toyota",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1541899481282-d31b556d089d?auto=format&fit=crop&w=900&q=85",
                            Model = "Yaris",
                            PricePerDay = 35m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Toyota",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85",
                            Model = "Land Cruiser",
                            PricePerDay = 145m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 10,
                            Brand = "BMW",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=900&q=85",
                            Model = "3 Series",
                            PricePerDay = 85m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 11,
                            Brand = "BMW",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=900&q=85",
                            Model = "X3",
                            PricePerDay = 90m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 12,
                            Brand = "BMW",
                            CategoryId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=85",
                            Model = "7 Series",
                            PricePerDay = 180m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Mercedes",
                            CategoryId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=900&q=85",
                            Model = "E-Class",
                            PricePerDay = 140m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Mercedes",
                            CategoryId = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1614162692292-7ac56d7f371e?auto=format&fit=crop&w=900&q=85",
                            Model = "S-Class",
                            PricePerDay = 220m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Mercedes",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=85",
                            Model = "GLC",
                            PricePerDay = 125m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Mercedes",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=85",
                            Model = "GLE",
                            PricePerDay = 155m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Audi",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=900&q=85",
                            Model = "A3",
                            PricePerDay = 70m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Audi",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
                            Model = "A4",
                            PricePerDay = 85m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Audi",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=85",
                            Model = "Q3",
                            PricePerDay = 80m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Audi",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
                            Model = "Q5",
                            PricePerDay = 100m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Hyundai",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=85",
                            Model = "Elantra",
                            PricePerDay = 42m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Hyundai",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1489824904134-933ca8c2ff1d?auto=format&fit=crop&w=900&q=85",
                            Model = "Sonata",
                            PricePerDay = 50m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Hyundai",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=85",
                            Model = "Tucson",
                            PricePerDay = 58m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Hyundai",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=900&q=85",
                            Model = "Santa Fe",
                            PricePerDay = 68m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Hyundai",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=85",
                            Model = "Accent",
                            PricePerDay = 32m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Kia",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=900&q=85",
                            Model = "Cerato",
                            PricePerDay = 40m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Kia",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
                            Model = "Sportage",
                            PricePerDay = 55m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Kia",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
                            Model = "Sorento",
                            PricePerDay = 70m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Kia",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=85",
                            Model = "K5",
                            PricePerDay = 52m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Kia",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1541899481282-d31b556d089d?auto=format&fit=crop&w=900&q=85",
                            Model = "Picanto",
                            PricePerDay = 28m,
                            Status = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Ford",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=85",
                            Model = "Focus",
                            PricePerDay = 38m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Ford",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1489824904134-933ca8c2ff1d?auto=format&fit=crop&w=900&q=85",
                            Model = "Fusion",
                            PricePerDay = 45m,
                            Status = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Ford",
                            CategoryId = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1584345604476-8ec5e12dc395?auto=format&fit=crop&w=900&q=85",
                            Model = "Mustang",
                            PricePerDay = 150m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Ford",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85",
                            Model = "Explorer",
                            PricePerDay = 85m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Ford",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=85",
                            Model = "Escape",
                            PricePerDay = 60m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Honda",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85",
                            Model = "Civic",
                            PricePerDay = 48m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Honda",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=85",
                            Model = "Accord",
                            PricePerDay = 55m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Honda",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=900&q=85",
                            Model = "CR-V",
                            PricePerDay = 62m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Honda",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=900&q=85",
                            Model = "City",
                            PricePerDay = 36m,
                            Status = 2,
                            Year = 2023
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Honda",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=85",
                            Model = "HR-V",
                            PricePerDay = 52m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Nissan",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1541899481282-d31b556d089d?auto=format&fit=crop&w=900&q=85",
                            Model = "Sunny",
                            PricePerDay = 30m,
                            Status = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Nissan",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=900&q=85",
                            Model = "Sentra",
                            PricePerDay = 40m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Nissan",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=900&q=85",
                            Model = "Altima",
                            PricePerDay = 48m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Nissan",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=900&q=85",
                            Model = "X-Trail",
                            PricePerDay = 65m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Nissan",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85",
                            Model = "Patrol",
                            PricePerDay = 160m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Chevrolet",
                            CategoryId = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1489824904134-933ca8c2ff1d?auto=format&fit=crop&w=900&q=85",
                            Model = "Malibu",
                            PricePerDay = 46m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Chevrolet",
                            CategoryId = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=85",
                            Model = "Cruze",
                            PricePerDay = 38m,
                            Status = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Chevrolet",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=85",
                            Model = "Tahoe",
                            PricePerDay = 110m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Chevrolet",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=900&q=85",
                            Model = "Captiva",
                            PricePerDay = 58m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Chevrolet",
                            CategoryId = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=85",
                            Model = "Equinox",
                            PricePerDay = 62m,
                            Status = 0,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Luxury"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Car", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reservation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Car", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
