// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    partial class CarRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/bmw-5-series.jpg",
                            Model = "5 Series",
                            PricePerDay = 95m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes",
                            CategoryId = 5,
                            ImageUrl = "/images/cars/mercedes-c-class.jpg",
                            Model = "C Class",
                            PricePerDay = 120m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Toyota",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/toyota-rav4.jpg",
                            Model = "RAV4",
                            PricePerDay = 65m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Audi",
                            CategoryId = 5,
                            ImageUrl = "/images/cars/audi-a6.jpg",
                            Model = "A6",
                            PricePerDay = 110m,
                            Status = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BMW",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/bmw-x5.jpg",
                            Model = "X5",
                            PricePerDay = 105m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Toyota",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/toyota-camry.jpg",
                            Model = "Camry",
                            PricePerDay = 55m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Toyota",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/toyota-corolla.jpg",
                            Model = "Corolla",
                            PricePerDay = 45m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Toyota",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/toyota-yaris.jpg",
                            Model = "Yaris",
                            PricePerDay = 35m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Toyota",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/toyota-land-cruiser.jpg",
                            Model = "Land Cruiser",
                            PricePerDay = 145m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 10,
                            Brand = "BMW",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/bmw-3-series.jpg",
                            Model = "3 Series",
                            PricePerDay = 85m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 11,
                            Brand = "BMW",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/bmw-x3.jpg",
                            Model = "X3",
                            PricePerDay = 90m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 12,
                            Brand = "BMW",
                            CategoryId = 5,
                            ImageUrl = "/images/cars/bmw-7-series.jpg",
                            Model = "7 Series",
                            PricePerDay = 180m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Mercedes",
                            CategoryId = 5,
                            ImageUrl = "/images/cars/mercedes-e-class.jpg",
                            Model = "E-Class",
                            PricePerDay = 140m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Mercedes",
                            CategoryId = 5,
                            ImageUrl = "/images/cars/mercedes-s-class.jpg",
                            Model = "S-Class",
                            PricePerDay = 220m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Mercedes",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/mercedes-glc.jpg",
                            Model = "GLC",
                            PricePerDay = 125m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Mercedes",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/mercedes-gle.jpg",
                            Model = "GLE",
                            PricePerDay = 155m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Audi",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/audi-a3.jpg",
                            Model = "A3",
                            PricePerDay = 70m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Audi",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/audi-a4.jpg",
                            Model = "A4",
                            PricePerDay = 85m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Audi",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/audi-q3.jpg",
                            Model = "Q3",
                            PricePerDay = 80m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Audi",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/audi-q5.jpg",
                            Model = "Q5",
                            PricePerDay = 100m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Hyundai",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/hyundai-elantra.jpg",
                            Model = "Elantra",
                            PricePerDay = 42m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Hyundai",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/hyundai-sonata.jpg",
                            Model = "Sonata",
                            PricePerDay = 50m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Hyundai",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/hyundai-tucson.jpg",
                            Model = "Tucson",
                            PricePerDay = 58m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Hyundai",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/hyundai-santa-fe.jpg",
                            Model = "Santa Fe",
                            PricePerDay = 68m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Hyundai",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/hyundai-accent.jpg",
                            Model = "Accent",
                            PricePerDay = 32m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Kia",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/kia-cerato.jpg",
                            Model = "Cerato",
                            PricePerDay = 40m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Kia",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/kia-sportage.jpg",
                            Model = "Sportage",
                            PricePerDay = 55m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Kia",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/kia-sorento.jpg",
                            Model = "Sorento",
                            PricePerDay = 70m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Kia",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/kia-k5.jpg",
                            Model = "K5",
                            PricePerDay = 52m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Kia",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/kia-picanto.jpg",
                            Model = "Picanto",
                            PricePerDay = 28m,
                            Status = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Ford",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/ford-focus.jpg",
                            Model = "Focus",
                            PricePerDay = 38m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Ford",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/ford-fusion.jpg",
                            Model = "Fusion",
                            PricePerDay = 45m,
                            Status = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Ford",
                            CategoryId = 3,
                            ImageUrl = "/images/cars/ford-mustang.jpg",
                            Model = "Mustang",
                            PricePerDay = 150m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Ford",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/ford-explorer.jpg",
                            Model = "Explorer",
                            PricePerDay = 85m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Ford",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/ford-escape.jpg",
                            Model = "Escape",
                            PricePerDay = 60m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Honda",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/honda-civic.jpg",
                            Model = "Civic",
                            PricePerDay = 48m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Honda",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/honda-accord.jpg",
                            Model = "Accord",
                            PricePerDay = 55m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Honda",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/honda-cr-v.jpg",
                            Model = "CR-V",
                            PricePerDay = 62m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Honda",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/honda-city.jpg",
                            Model = "City",
                            PricePerDay = 36m,
                            Status = 2,
                            Year = 2023
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Honda",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/honda-hr-v.jpg",
                            Model = "HR-V",
                            PricePerDay = 52m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Nissan",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/nissan-sunny.jpg",
                            Model = "Sunny",
                            PricePerDay = 30m,
                            Status = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 42,
                            Brand = "Nissan",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/nissan-sentra.jpg",
                            Model = "Sentra",
                            PricePerDay = 40m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 43,
                            Brand = "Nissan",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/nissan-altima.jpg",
                            Model = "Altima",
                            PricePerDay = 48m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Nissan",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/nissan-x-trail.jpg",
                            Model = "X-Trail",
                            PricePerDay = 65m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Nissan",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/nissan-patrol.jpg",
                            Model = "Patrol",
                            PricePerDay = 160m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Chevrolet",
                            CategoryId = 1,
                            ImageUrl = "/images/cars/chevrolet-malibu.jpg",
                            Model = "Malibu",
                            PricePerDay = 46m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Chevrolet",
                            CategoryId = 4,
                            ImageUrl = "/images/cars/chevrolet-cruze.jpg",
                            Model = "Cruze",
                            PricePerDay = 38m,
                            Status = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Chevrolet",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/chevrolet-tahoe.jpg",
                            Model = "Tahoe",
                            PricePerDay = 110m,
                            Status = 0,
                            Year = 2024
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Chevrolet",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/chevrolet-captiva.jpg",
                            Model = "Captiva",
                            PricePerDay = 58m,
                            Status = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 50,
                            Brand = "Chevrolet",
                            CategoryId = 2,
                            ImageUrl = "/images/cars/chevrolet-equinox.jpg",
                            Model = "Equinox",
                            PricePerDay = 62m,
                            Status = 0,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Luxury"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Car", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Reservation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Car", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
